microsoft/azure-pipelines-tool-lib

- package.json
Build and test are passing locally.
We haven't released this in a bit, so this change(obviously :)) and the status code in the exception dictionary haven't been published. When you get a chance if you can publish this and let me know then I can make the changes to reference the new version in vsts-tasks.
I also removed the carat from the typed rest client version, seems better to be explicit.
Thanks!
> Update typed-rest-client version.

- .gitignore
- package-lock.json
- package.json
- test/toolTests.ts
- tool.ts
While trying to download a tools exe from Github releases using toolLib.downloadTool I got the following error: UnhandledPromiseRejectionWarning: Error: Unexpected HTTP response: 302. Github was redirecting met to an AWS blob which seems perfectly fine to me but toolLib.downloadTool only accepts HTTP 200.
I updated typed-rest-client to 1.0.7 to allow toolLib.downloadTool to work with HTTP redirects.
> Use typed-rest-client 1.0.7 to allow toolLib.downloadTool to work with redirects.

- package.json
- test/toolTests.ts
- tool.ts
This was discovered in #35 
The bug was added when we made a change to handle redirects. As part of that change we refactored some of the code to prevent opening a file for write until we had successfully make the HTTP request. During this refactoring we wanted to make sure the file was correctly closed, even in error cases. When doing this there was a finally added inside the file open callback. The finally was always getting executed immediately as the stream finish code is done inside an event handler and runs asynchronously.
The issue wasn't caught because our L0 tests only check that a downloaded file exists, they do not check the file size :) I fixed that and added a test to check that we can successfully download a file after a redirect.
> Fix bug with downloadTool creating an empty file

- package-lock.json
- package.json
- test/toolTests.ts
- tool.ts
Added option destination directory to the extractTar and extractZip methods.  This allows for vsts-tasks build tasks to use these methods when a specific destination directory needs to be specified.
Ran npm tests and verified on azure vm.
> Added option destination directory to the extractTar and extractZip methods

- package-lock.json
- package.json
- test/toolTests.ts
- tool.ts
Could you please update the typed-rest-client to 1.0.9 so it could handle redirection with status code 303?
> Update typed-rest-client to 1.0.9, and add unittest to cover 303 case.

- test/tests/toolTests.ts
- tool.ts
Adding an optional input of http client handlers to the downloadTool to allow an authenticated download.
> Add handlers option to downloadTool

- azure-pipelines.yml
The last commit on https://github.com/microsoft/azure-pipelines-tool-lib/pull/60 broke it so that it gives a parse error - https://dev.azure.com/ms/azure-pipelines-tool-lib/_build/results?buildId=59519&view=results
> Fix broken build

- tool.ts
z flag forces gz and overrides file type detection.  fixes https://github.com/microsoft/azure-pipelines-tool-lib/issues/69
> removing 'z' flag for tar invocation 

- Localize/localize-pipeline.yml
- open-pullrequest.ps1
**Task name**: Localization pipeline definition
**Description**: 
Added schedule trigger to run the localization pipeline on the third week of a sprint on Mondays at 8 a.m. UTC,
Added Slack notifications about successful and failed builds.
**Documentation changes required:** No
**Added unit tests:** No
**Attached related issue:** [#877](https://github.com/microsoft/build-task-team/issues/877)
> Set up schedule and notifications for the localization pipeline

- package-lock.json
- package.json
Fix CVE-2021-23358 by updating underscore (dependency of typed-rest-client)
> Bump typed-rest-client

- azure-pipelines-steps.yml
- package.json
- test/units/toolTests.ts
The CI for releases/0.x is failing for these reasons:
1. Node versions used for building and testing are inconsistent across systems; this is why we use node 6 everywhere now
2. Node 6 updates `@types/xml2js` to 0.4.8 from 0.4.4, which causes typescript build failures; this is why we locked it to 0.4.4
3. The zip installation tests exceed timeouts on windows
> Fix ci failures on releases/0.x

- azure-pipelines-steps.yml
- test/units/toolTests.ts
Currently the CI is failing for two reasons:
1. We're testing with node 6, but typescript 4 does not support node 6; switching to node 10 because tool-lib 1.x is supposed to work on node 10
2. The zip installation tests exceed timeouts on windows
> Fix ci failures

- azure-pipelines.yml
We need to update the image in the CI from `ubuntu-16.04` at least to `ubuntu-18.04` since
```
Ubuntu 16.04 LTS environment is deprecated and will be removed on September 20, 2021.
```
> Update ubuntu image in the CI

- Localize/localize-pipeline.yml
- open-pullrequest.ps1
- send-notifications.ps1
**IMPORTANT - The PR must be completed with PR https://github.com/microsoft/azure-pipelines-tool-lib/pull/146 at the same time.**
---
Move notifications about Tool-lib Localization PR from Slack to MS Teams. Content of notifications was updated.
> Move notifications about Tool-lib Localization PR from Slack to MS Teams - Part 1

- open-pullrequest.ps1
- send-notifications.ps1
**IMPORTANT - The PR must be completed with PR https://github.com/microsoft/azure-pipelines-tool-lib/pull/145 at the same time.**
---
Move notifications about Tool-lib Localization PR from Slack to MS Teams. Content of notifications was updated.
> Move notifications about Tool-lib Localization PR from Slack to MS Teams - Part 2

- package-lock.json
- package.json
- tool.ts
typed-rest-client doesn't support `Authorization: token ...` by default, so we need to pass it as an HTTP header.
This is needed for python release binary downloading from the [python versions registry](https://github.com/actions/python-versions).
> Add support for custom authorization header value

- package-lock.json
- package.json
Starting from Mocha 9.0.0 node 10 is no longer supported - https://github.com/mochajs/mocha/releases/tag/v9.0.0
Downgrade Mocha version to 6.2.3 to prevent possible issues with node 10
**Why not 8.4.0?**: 8.4.0 version contains 1 security vulnerability while the 6.2.3 is clear and more safe to upgrade from 5.x
**Checklist:**
> Downgrade Mocha to 6.2.3 to prevent issues with node 10

- README.md
- azure-pipelines-steps.yml
- azure-pipelines.yml
- package-lock.json
- package.json
- test/units/toolTests.ts
In order to migrate tasks to the Node16 execution handler, we have to update the azure-pipelines-tool-lib itself to support the Node16 runtime.
- Updated dev dependencies
- Updated package-lock.json to version 2 to unlock the ability for deterministic and reproducible builds
- Updated pipeline to use Node 16, MacOS 10.15, windows 2019
- Updated pipeline to build an artifact in releases/2.x branch
- Fixed one test
- Changes have been tested on Linux, MacOS, Windows: 
by unit-tests
manually as part of some task. Used tasks and cases are described [here](https://github.com/microsoft/azure-pipelines-tool-lib/pull/164#issuecomment-1176533810)
- Enough test coverage for changes and current test coverage for the task doesn't look poor
- I didn't find any breaking changes
- There are no other …
> Migrating to the Node 16 runtime

- Strings/resources.resjson/fr-FR/resources.resjson
- Strings/resources.resjson/ru-RU/resources.resjson
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/ceLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
> Localized file check-in by OneLocBuild Task: Build definition ID 10929: Build ID 19000639

- CHANGELOG.md
- package.json
- tool.ts
**Description of issue:**
Customers reported that sometimes `NodeTool` task silently passes without completing of downloading `node.js`. It happens due to the fact that there is no logic to handle `http` related errors
**Description of fix:**
I have added logic to handle `http` errors in function `downloadTool`
**How changes were tested:**
Looks like `nodejs.org` is throttling some customers and aborting their requests. I simulated such situation via tool `TCPView` on windows and `dsniff` on Ubuntu. I limited my network connection by npm-package `@sitespeed.io/throttle` to get more time to interact with TCP connections
**Screenshots:**
_Before_
_After_
> Added logic to handle HTTP-errors during file downloading

- CHANGELOG.md
- package-lock.json
- package.json
- tool.ts
**Description of issue:**
`Node10` doesn't emit event `error` when connection was aborted
**Description of fix:**
Added logic to subscribe on event `aborted` and reject promise to throw an exception. Exception is `Aborted` as it generated in `Node16` to make it consistent.
**How it was tested:**
Tested on self-hosted agent by replacing original code of `tool-lib` with my changes in `NodeTool` task.
_Before fix:_
_After fix:_
Successful run: https://abtttestorg.visualstudio.com/Other/_build/results?buildId=6265
Run with throttling issues: https://abtttestorg.visualstudio.com/Other/_build/results?buildId=6262
> Add subscription on "aborted" event for Node10 compatibility

- package-lock.json
- package.json
- tool.ts
Sometimes we have a case then message stream was destroyed before we subscribed to it's events. 
This leads to case when we don't raise the promise.resolve and nodejs process exits with code 0.
fix should resolve the issue: https://github.com/microsoft/azure-pipelines-tasks/issues/20508
> downloadTool fix: pre-check aborted & destroyed props

- .azure-pipelines/common-steps.yml
- .azure-pipelines/release-pipeline.yml
- azure-pipelines.yml
- package.json
This change implements automated publishing to https://www.npmjs.org for the azure-pipelines-tool-lib-test package.
It follows a Windows-only publishing strategy and integrates the release pipeline for azure-pipeline-tool-lib with the public npm registry.
Work-Item: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2303569
Pipeline: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=30365114&view=results
> Release Pipeline Integration for azure-pipeline-tool-lib to Public Registry | Part#2
