- package-lock.json
- test/toolTests.ts
> Fix tests, update package lock.

- docs/overview.md
Some of the content here seems to reflect an old design that is not what we have now.  I've fixed up the examples and added detail to bring it up-to-date.
I also added some detail on how to lay out the tool cache with your own tool versions so they will work with the tool lib.
> Update documentation on tool lib

- package-lock.json
- package.json
There are basically no significant breaking changes and 3.1.5 is stable. Enables some new features for future development.
> Update to typescript 3.1.5

- .gitignore
- package-lock.json
- package.json
- test/units/toolTests.ts
- tool.ts
Per [#10170](https://github.com/microsoft/azure-pipelines-tasks/issues/10170)
> Add Retries to Tool Retrieval

- azure-pipelines-steps.yml
- azure-pipelines.yml
- package-lock.json
> Update ci to publish package.

- docs/overview.md
This uses the correct value for the tools cache location. Fixes #62.
> Fix tool cache location (#62)

- azure-pipelines.yml
- package-lock.json
- package.json
- test/tests/toolTests.ts
- test/units/toolTests.ts
Use the most recent version.
Fixes #71
> Bump typed rest client

- Localize/loc/de-de/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/en-US/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/es-es/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/fr-fr/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/it-IT/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ja-jp/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ko-KR/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ru-RU/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/zh-CN/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/zh-TW/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_5ca4c881-b8be-42d9-aa82-e7f8fca618fc_20210128191417905 to Localization with localized lcls
> LEGO: Pull request from lego/hb_5ca4c881-b8be-42d9-aa82-e7f8fca618fc_20210128191417905 to Localization

- package-lock.json
- package.json
- test/units/toolTests.ts
Merged `releases/1.x` branch into master.
Changed package version (increased major version, get rid of preview postfix.
Created a backup branch: [releases/0.x](https://github.com/microsoft/azure-pipelines-tool-lib/tree/releases/0.x)
> Prepared for release a new 1.0.0 version

- Localize/loc/ja-jp/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/zh-TW/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_5ca4c881-b8be-42d9-aa82-e7f8fca618fc_20210209150554091 to Localization with localized lcls
> LEGO: Pull request from lego/hb_5ca4c881-b8be-42d9-aa82-e7f8fca618fc_20210209150554091 to Localization

- Localize/loc/ko-KR/Strings/resources.resjson/en-US/resources.resjson.lcl
Re-created PR not merged previously - https://github.com/microsoft/azure-pipelines-tool-lib/pull/83
> LEGO: check in for Localization to temporary branch.

- package-lock.json
package-lock.json was recreated from scratch which caused build issues; I've checked out the releases/0.x branch before the changes, bumped typed-rest-client and ran `npm i` to get this package-lock.json
> Fix invalid package-lock

- Localize/LocProject.json
- Localize/localize-pipeline.yml
Returned back localize-pipeline.yml and LocProject.json files - since they were removed by auto-merge from master - after we removed related files in master branch.
> Localization branch - returned back localize-pipeline.yml and LocProject.json files

- Localize/loc/de-DE/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/de-de/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/en-US/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/es-ES/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/es-es/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/fr-FR/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/fr-fr/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/it-IT/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ja-JP/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ja-jp/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/ru-RU/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/zh-CN/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/loc/zh-TW/Strings/resources.resjson/en-US/resources.resjson.lcl
- Localize/localize-pipeline.yml
Recovered lcl files content - replaced by English strings.
> Recovered lcl files content

- package-lock.json
- package.json
Resolved vulnerabilities in dependencies this library.
Updated dependencies:
- `azure-pipelines-task-lib` to 3.1.10
- `typed-rest-client` to 1.8.6
- `shelljs` to 0.8.5
Component Governence - [results](https://dev.azure.com/v-igolubev/Test/_componentGovernance/39122?_a=alerts&typeId=283267&alerts-view-option=active)
*To resolve vulnerabilities for `string_decoder` package, need to update this package in azure-pipelines-task-lib.
> Resolve security alerts

- azure-pipelines.yml
- package-lock.json
- package.json
Update for `azure-pipelines-tool-lib` dependency
- Update for `azure-pipelines-tool-lib` dependency
- Added publish artifact step
- Changes have been tested on Linux, MacOS, Windows: 
by unit-tests
manually as part of some task. Used tasks and cases are described [here](https://github.com/microsoft/azure-pipelines-tool-lib/pull/164#issuecomment-1176533810)
- Enough test coverage for changes and current test coverage for the task doesn't look poor
- I didn't find any breaking changes
- There are no other concerns
- I haven't discovered any new uncovered test/use cases
> Update task lib

- README.md
Since at the moment there is active development in two branches, master and releases/2.x, it is necessary to make a note about this
- Updated README.md
> Update readme.md according to the current state of development

- package-lock.json
- package.json
- tool.ts
Redact signature for a sas url
> Redact signature for a sas url

- package-lock.json
- package.json
- test/tests/toolTests.ts
- tool.ts
- Added retry method for downloading tool function
> [downloadTool] - Add retry logic for when downloading files

- .npmrc
- azure-pipelines-steps.yml
- package-lock.json
**Description**: This PR adds **.npmrc** to all packages in the repository to consume packages from the internal feed.
**Related**: [AB#2197030](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2197030)
> Migration to CFS
